In [12]:
import pandas as pd
import openpyxl

In [ ]:
df = pd.read_csv('pandascsv.csv')

In [81]:
df = pd.read_excel('pandascsv.xlsx')

In [ ]:
dictionary = I AM DEFINING A DICTIONARY HERE BUT YOU DON'T KNOW HOW TO BUT DON'T WORRY YOU WILL THIS AFTERNOON
df = pd.DataFrame(dictionary)

In [9]:
df

      Name  Age           City  Salary
0     John   25       New York   50000
1    Alice   32  San Francisco   75000
2  Michael   28        Chicago   60000
3     Emma   35    Los Angeles   80000

In [16]:
df.head(3)

      Name  Age           City  Salary
0     John   25       New York   50000
1    Alice   32  San Francisco   75000
2  Michael   28        Chicago   60000

In [17]:
df.tail(2)

      Name  Age         City  Salary
2  Michael   28      Chicago   60000
3     Emma   35  Los Angeles   80000

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
 3   Salary  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [23]:
df.shape

(4, 4)

In [24]:
df.describe()

             Age        Salary
count   4.000000      4.000000
mean   30.000000  66250.000000
std     4.396969  13768.926368
min    25.000000  50000.000000
25%    27.250000  57500.000000
50%    30.000000  67500.000000
75%    32.750000  76250.000000
max    35.000000  80000.000000

In [31]:
column = df['Salary']

In [37]:
column.tolist()

[50000, 75000, 60000, 80000]

In [39]:
list_of_columns = ['Name','Age']
df[list_of_columns]

      Name  Age
0     John   25
1    Alice   32
2  Michael   28
3     Emma   35

In [41]:
df2 = df[['Name','Age']]

In [42]:
df2

      Name  Age
0     John   25
1    Alice   32
2  Michael   28
3     Emma   35

In [45]:
df

      Name  Age           City  Salary
0     John   25       New York   50000
1    Alice   32  San Francisco   75000
2  Michael   28        Chicago   60000
3     Emma   35    Los Angeles   80000

In [52]:
city_of_interest = df.loc[3,'City']

In [53]:
city_of_interest

'Los Angeles'

In [55]:
list_df = [["John", 25, "New York", 50000]]

In [56]:
list_df[0]

['John', 25, 'New York', 50000]

In [57]:
df.iloc[0]

Name          John
Age             25
City      New York
Salary       50000
Name: 0, dtype: object

In [58]:
df

      Name  Age           City  Salary
0     John   25       New York   50000
1    Alice   32  San Francisco   75000
2  Michael   28        Chicago   60000
3     Emma   35    Los Angeles   80000

In [60]:
df['Relationship Status'] = 'Single'

In [61]:
df

      Name  Age           City  Salary Relationship Status
0     John   25       New York   50000              Single
1    Alice   32  San Francisco   75000              Single
2  Michael   28        Chicago   60000              Single
3     Emma   35    Los Angeles   80000              Single

In [62]:
df['Relationship Status'] = ['Single', 'Married', 'Widowed', 'No comment']

In [63]:
df

      Name  Age           City  Salary Relationship Status
0     John   25       New York   50000              Single
1    Alice   32  San Francisco   75000             Married
2  Michael   28        Chicago   60000             Widowed
3     Emma   35    Los Angeles   80000          No comment

In [64]:
df.loc[df['Name'] != 'John', 'Relationship Status'] = 'Its Complicated'

In [65]:
df

      Name  Age           City  Salary Relationship Status
0     John   25       New York   50000     Its Complicated
1    Alice   32  San Francisco   75000             Married
2  Michael   28        Chicago   60000             Widowed
3     Emma   35    Los Angeles   80000          No comment

In [66]:
df.loc[df['Salary'] >= 65000, 'City'] = 'Stuttgart'

In [67]:
df

      Name  Age      City  Salary Relationship Status
0     John   25  New York   50000     Its Complicated
1    Alice   32    Munich   75000             Married
2  Michael   28    Munich   60000             Widowed
3     Emma   35    Munich   80000          No comment

In [71]:
df = df.drop(columns=['Relationship Status'])

In [72]:
df

      Name  Age      City  Salary
0     John   25  New York   50000
1    Alice   32    Munich   75000
2  Michael   28    Munich   60000
3     Emma   35    Munich   80000

In [78]:
df = df.sort_values(by='Salary')

In [79]:
df

      Name  Age      City  Salary
0     John   25  New York   50000
2  Michael   28    Munich   60000
1    Alice   32    Munich   75000
3     Emma   35    Munich   80000

In [82]:
df

      Name  Age           City  Salary
0     John   25       New York   50000
1    Alice   32  San Francisco   75000
2  Michael   28        Chicago   60000
3     Emma   35    Los Angeles   80000

In [84]:
grouped = df.groupby('City')

In [86]:
grouped.mean(numeric_only = True)

                Age   Salary
City
Chicago        28.0  60000.0
Los Angeles    35.0  80000.0
New York       25.0  50000.0
San Francisco  32.0  75000.0

In [87]:
grouped.sum(numeric_only = True)

               Age  Salary
City
Chicago         28   60000
Los Angeles     35   80000
New York        25   50000
San Francisco   32   75000

In [88]:
grouped.count()

               Name  Age  Salary
City
Chicago           1    1       1
Los Angeles       1    1       1
New York          1    1       1
San Francisco     1    1       1

In [89]:
df

      Name  Age           City  Salary
0     John   25       New York   50000
1    Alice   32  San Francisco   75000
2  Michael   28        Chicago   60000
3     Emma   35    Los Angeles   80000

In [92]:
df = df.replace('New York', 'Los Angeles')

In [93]:
df

      Name  Age           City  Salary
0     John   25    Los Angeles   50000
1    Alice   32  San Francisco   75000
2  Michael   28        Chicago   60000
3     Emma   35    Los Angeles   80000

In [94]:
grouped = df.groupby('City')

In [100]:
grouped.count()

               Name  Age  Salary
City
Chicago           1    1       1
Los Angeles       2    2       2
San Francisco     1    1       1

In [101]:
df

      Name  Age           City  Salary
0     John   25    Los Angeles   50000
1    Alice   32  San Francisco   75000
2  Michael   28        Chicago   60000
3     Emma   35    Los Angeles   80000

In [127]:
#list = ["eggs", "beans", "milk", "chocolate"]
for index, row in df.iterrows():
    print(row['Name'] + ' lives in ' + row['City'] + ' and he is ' + str(row['Age']) + ' years old.')

John lives in Los Angeles and he is 25 years old.
Alice lives in San Francisco and he is 32 years old.
Michael lives in Chicago and he is 28 years old.
Emma lives in Los Angeles and he is 35 years old.

In [ ]:
for i in range(len_df):
    df.iloc[i]......
    df2.iloc[i]

In [128]:
df = pd.read_csv('unesco_heritage_sites.csv')

In [132]:
df.columns.tolist()

['SiteID',
 'Name',
 'Country',
 'Category',
 'YearInscribed',
 'VisitorsPerYear',
 'Area_km2',
 'Threatened']

In [136]:
def get_column_name(df):
    list_of_columns = df.columns.tolist()
    return list_of_columns

In [137]:
get_column_name(df)

['SiteID',
 'Name',
 'Country',
 'Category',
 'YearInscribed',
 'VisitorsPerYear',
 'Area_km2',
 'Threatened']

In [141]:
df[df['Category'] == 'Cultural']

,SiteID,Name,Country,Category,YearInscribed,VisitorsPerYear,Area_km2,Threatened
0,1,Great Wall of China,China,Cultural,1987,10.0,21196.00,No
1,2,Machu Picchu,Peru,Cultural,1983,1.5,32.00,No
2,3,Pyramids of Giza,Egypt,Cultural,1979,14.0,16.00,No
4,5,Colosseum,Italy,Cultural,1980,7.6,0.02,No
6,7,Stonehenge,UK,Cultural,1986,1.3,0.03,No
7,8,Taj Mahal,India,Cultural,1983,8.0,0.17,No
9,10,Angkor Wat,Cambodia,Cultural,1992,2.6,162.60,No
11,12,Acropolis of Athens,Greece,Cultural,1987,2.0,3.04,No
13,14,Petra,Jordan,Cultural,1985,1.0,264.00,No
14,15,Eiffel Tower,France,Cultural,1991,6.9,0.01,No

In [145]:
def filter_by_category(df, category):
    new_df = df[df['Category'] == category]
    return new_df

In [146]:
filter_by_category(df, 'Cultural')

,SiteID,Name,Country,Category,YearInscribed,VisitorsPerYear,Area_km2,Threatened
0,1,Great Wall of China,China,Cultural,1987,10.0,21196.00,No
1,2,Machu Picchu,Peru,Cultural,1983,1.5,32.00,No
2,3,Pyramids of Giza,Egypt,Cultural,1979,14.0,16.00,No
4,5,Colosseum,Italy,Cultural,1980,7.6,0.02,No
6,7,Stonehenge,UK,Cultural,1986,1.3,0.03,No
7,8,Taj Mahal,India,Cultural,1983,8.0,0.17,No
9,10,Angkor Wat,Cambodia,Cultural,1992,2.6,162.60,No
11,12,Acropolis of Athens,Greece,Cultural,1987,2.0,3.04,No
13,14,Petra,Jordan,Cultural,1985,1.0,264.00,No
14,15,Eiffel Tower,France,Cultural,1991,6.9,0.01,No

In [ ]:
def count_sites_per_country(df, country):
    SOME STUFF
    return new_df